### ISSUE TITLE
Certain instance options are not optional

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#1]
Setting app and engine names are mandatory, otherwise instance creation just crashes. These should be checked or set to some default value (I propose second).

Perhaps a test should cover the permutation of set and not set values.

**Comment by charles-lunarg** [comment]
Fixed by making sure the const char *'s are not nullptr and using "" if they are. 
This was the original behavior, only, I was using std::string so nullptr's weren't possible. Since there was no pressing need to use std::string (layers and extensions all have static strings) I opted to only need const char *'s. Thank you for catching this, its a silly mistake on my part.
