### ISSUE TITLE
Allow vkb::Device::get_queue(vkb::QueueType::transferQueue) to return a graphics/compute queue as a fallback.

### ISSUE THREAD

**Issue by Diamond-D0gs** [charles-lunarg/vk-bootstrap#109]
The Vulkan spec specifies that drivers are not required to report that a queue family supports transfer capabilities despite the fact that if a queue family supports graphics or compute queues then it supports the ability to be a transfer queue.

[https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueueFlagBits.html#_description](url)

While it's not common to find devices with no queue families that report transfer capabilities, a fallback should be added to the function that returns a graphics/compute queue in such an event.

**Comment by charles-lunarg** [comment]
This is going to be closed with not-planned. This is because while this is technically true, its a bit of a weird corner of the spec that would probably cause surprising behavior to those who aren't familiar with it. Plus it'd be a bit hard to implement, since to query if a queue supports transfer ops, you'd also need to check if it supports graphics or compute ops.

Plus, with the queue rework PR, being able to query a queue that can do graphics + transfer, or compute + transfer is possible now.
