### ISSUE TITLE
`PhysicalDeviceSelector` should default to the Vulkan version of the instance

### ISSUE THREAD

**Issue by DethRaid** [charles-lunarg/vk-bootstrap#12]

**Comment by charles-lunarg** [comment]
My concern is when a developer has X version on their development machine, but when they ship to users, some of which have only Y version, it breaks.
Its an implicit assumption about what features are available, which may not always be available.

**Comment by DethRaid** [comment]
I don't agree. I don't have the same view into the Vulkan loader that you do, though, so there might be something I'm missing

I'm a Vulkan developer. I'm coding my application against Vulkan 1.2. I need to be able to load Vulkan 1.2 functions, and the device I'm running on needs to support those Vulkan 1.2 functions. From my perspective there's no sense loading Vulkan 1.2 function if the device I'm running on only supports 1.0, or vice versa - if I load Vulkan 1.0 functions, it's because I'm using Vulkan 1.0. Telling the device to use Vulkan 1.2 is fine I guess but my application won't be using Vulkan 1.2 functionality

I just don't see the use case where I, as an application developer, wants to have the Vulkan instance and device use different Vulkan versions

**Comment by charles-lunarg** [comment]
I actually misunderstood your comment initially. I now see that if you set "when requiring a vulkan instance version of 1.2, make the device vulkan 1.2 as well" which is a lot more reasonable. I first thought you meant setting the vulkan version to the one found on the system.

One of the problems about setting the loader version is that you can use a vulkan 1.2 device with a 1.1/1.0 loader. Imagine a case where the user has 2 gpu's on a user's system and only one device supports 1.2. For whatever reason when they installed the drivers for that gpu, the loader wasn't updated and is still a 1.1 loader. Then, when an instance is created, it has a version of 1.1. If the instance version must be 1.2, the app would fail to create an instance. But you still could create a 1.2 device regardless. Now, this is a corner case, but with how drivers and loaders interact not something I'd say is impossible.  

The subject of 'exported function symbols' brings up an important consideration. The above situation is a 'hard crash' instead of 'known error' if an app was using the exported symbols from the loader. Any 1.2 function calls when linked against a 1.1 loader will abort with undefined symbols because a 1.1 loader doesn't export 1.2 core function symbols. Loading the functions manually will make that a non issue (and should be done in any case for performance). 

I did go ahead and add the validation of the minor version of apiVersion to InstanceBuilder in the most recent commit.

**Comment by DethRaid** [comment]
Yeah I don't want to default to the Vulkan version of whatever driver happens to be installed, I want the devices to use the Vulkan version that I created the instance with

**Comment by charles-lunarg** [comment]
To refine the issue a bit:
After looking at the documentation for apiVersion in VkCreateInstanceInfo (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkApplicationInfo.html), it is apparent that an application wanting to use 1.2 device functionality must have an apiVersion set to 1.2. Any attempts to create a 1.2 device should fail if the apiVersion wasn't set to 1.2. But just because a 1.2 instance level is set doesn't necessarily mean a 1.2 device is required. Making the assumption that setting a 1.2 instance level requires 1.2 capable devices is the issue I'm mainly grappling with.

**Comment by charles-lunarg** [comment]
This feature request has been added by first changing `set_api_version` of InstanceBuilder to `require_api_version` to make it obvious that the listed version is a requirement. Since you need to set the Instance apiVersion to X to use any devices with X version, it is reasonable to assume that is what people want. 
It has been included in the latest commit, so I will close the issue.
