### ISSUE TITLE
Support for delayed surface creation

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#15]
Is it possible to let vk-bootstrap know that the device will not be headless, but the surface will be created later?

I think this needs:
 - enabling surface extensions without a surface
 - creating all available queue families
 - asking vk-bootstrap if the later created surface is actually compatible with the physical device

**Comment by charles-lunarg** [comment]
This is very possible.
The surface extensions should already be created regardless of a provided surface handle. The extensions are based on the platform defines, which I would like to revisit in the future.
Enabling all the queue families is certainly an option, and probably the right thing to do in most cases. It shouldn't be a performance issue to enable them all anyways, and that simplifies device creation logic significantly.
"asking later" should just be a helper function. Not to challenging at all.

**Comment by charles-lunarg** [comment]
I have added a "defer_surface_initialization" option to the physical device selector and (in a different commit) made all queue families enabled. 
The added option will bypass checking if a surface and physical device are compatible.
Can you confirm that this does what is desired before I can close the issue?

**Comment by charles-lunarg** [comment]
I added `defer_surface_initialization` to PhysicalDeviceSelector and it prevents physical device selection from using surface information in its decision, effectively letting the surface be created later. The queues also are always going to be created (as a simplification to the queue interface), so that shouldn't be an issue. And the swapchain helpers support passing in exactly the data needed so there is no issue there.
Can you look at the most changes and let me know if its adequate before I close the issue?

**Comment by martty** [comment]
Looks like so! Though I don't have code to test it right now, but I'll reopen if it doesn't work :). Thanks!
