### ISSUE TITLE
Triangle example: why wait for the image_in_flight fence?

### ISSUE THREAD

**Issue by yoanlcq** [charles-lunarg/vk-bootstrap#164]
Hi,

Referring to [the Triangle example](https://github.com/charles-lunarg/vk-bootstrap/blob/1fea63645a799689e4d8384df2b809f884b20f88/example/triangle.cpp#L477)

In short: I'm wondering why there is a need for the `image_in_flight` fence at all, whereas it appears to me that `available_semaphore` is enough for this task.

The point is to wait for all commands on the current swapchain image to have completed, however, I think that this wait only needs to occur on the GPU, and the example is already doing it (by setting `data.available_semaphores[data.current_frame]` as a wait semaphore for the submit).

However, I am basing this on the assumption that the semaphore passed to `vkAcquireNextImageKHR()` _will_ fully wait for the previous present of that image to have completed (which, in turn, has waited for the commands in-flight for that image to have completed, thanks to `finished_semaphore`).  

I am considering removing this wait in my own project, which is based on the mentioned example, but I'm worried that is was placed there for a good reason that I am missing, and I would be grateful if you could shine a light on this.

Thank you very much in advance!

**Comment by charles-lunarg** [comment]
This is a generally tricky topic, and frankly this code is mostly an example of how to use 'vk-bootstrap' rather than how to draw a triangle with exact synchronization.

The code's structure (wrt to sync) here is taken from an old version of vulkan-tutorial, which pre-recorded command buffers. 

> However, I am basing this on the assumption that the semaphore passed to vkAcquireNextImageKHR() will fully wait for the previous present of that image to have completed.

This is a baseless and incorrect assumption. vkAcquireNextImageKHR has no direct connection to the most previous presentation. It is an unfortunate situation that the vulkan swapchain does not make good guarantees about when the presentation(s) have completed, as it currently is unspecified. Like, you have no real good way of knowing when a present has finished.

I would NOT remove the wait, because 1. you should be re-recording command buffers every frame 2. which must not be in use at that time and 3. it makes sure that the semaphore you provide with vkAcquireNextImageKHR is actually available.

**Comment by yoanlcq** [comment]
Thank you for the reply and advice. That made me realize where I was wrong and after careful re-reading, I understand why the wait is needed.

This is because the example selects which command buffer to send via `image_index`, but in my application it's using `current_frame` (the equivalent, at least) and I missed this difference from the example.  

Also, you made me realize that I didn't actually care about the "present" being completed, but rather that the image is available for use at all; I incorrectly glued both together in my head, but it's wrong, since effectively you could have a present mode that results in tearing, and it could be wanted.  
What my code actually wants "the image can be used" rather than "was the image finished being shown entirely on screen", and in that regard, the spec is clear enough to me.

All in all this was a misunderstanding on my part, but at least this clarifies that there is no "magic" about this, due to some grey areas of the spec or something.  
So I think I can remove the wait in my application (after careful re-read), and the example should remain as it is.

Thanks again.

**Comment by charles-lunarg** [comment]
Works for me!

I'm hopeful that a 'fixed' swapchain extension could come out, removing a lot of the headache's around swapchains. VK_KHR_present_wait & VK_KHR_present_id are a help but aren't a solution.

If you want to see a *much* more complex swapchain example, check out the `swapchain` branch on this repo. The branch adds a 'swapchain management library' to vk-bootstrap, but I never got it in a state I was happy with. Too many issues with the spec and whittled down my motivation to a stall. The vk-triangle example is where I tested out the swapchain library.
