### ISSUE TITLE
v0.6 is incompatible with latest vulkan release

### ISSUE THREAD

**Issue by NicolasCaous** [charles-lunarg/vk-bootstrap#188]
When trying to build a cmake project with vulkan version 1.3.236.0 with vk-bootstrap v0.6, it fails because vulkan removed some identifiers that v0.6 depends on.

This however is not a problem on the master branch. The master branch works perfectly with the vukan version mentioned above. So the solution is to just create a new release v0.7

**Comment by charles-lunarg** [comment]
Thats odd.
Can you list the identifiers which were removed?
The Vulkan Spec is meant to be backwards compatible, so that shouldn't happen, unless I am misunderstanding you.

**Comment by NicolasCaous** [comment]
@charles-lunarg Yes

Here is my CMake file:

```
FetchContent_Declare(
    fetch_vk_bootstrap
    GIT_REPOSITORY https://github.com/charles-lunarg/vk-bootstrap
    GIT_TAG        v0.6
)
FetchContent_MakeAvailable(fetch_vk_bootstrap)
```

Yields these errors:

![image](https://user-images.githubusercontent.com/24411365/210007818-1aa2a2d6-4c79-4952-a7db-0cd22786266a.png)

So the offending identifiers are:
  * VkVideoGetMemoryPropertiesKHR
  * VkVideoBindMemoryKHR
  * VkVideoGetMemoryPropertiesKHR
  * VkVideoBindMemoryKHR

And they don't exist on the master branch.

**Comment by charles-lunarg** [comment]
Ah I see, so the vulkan headers did some non-backwards compatible changes. Thank you for reporting it!

This is unfortunate because without moving the tag, there really isn't a fix for it. I think adding  `defined(VK_ENABLE_BETA_EXTENSIONS)` to those functions should resolve that (assuming users aren't using the beta-extensions). It'd be good to do that going forward too, but not sure about backporting it.

I *would* have updated this issue sooner, but I was OOO so wasn't able to properly investigate nor respond.

**Comment by NicolasCaous** [comment]
You are welcome! :)

**Comment by charles-lunarg** [comment]
Looking into this, I can only reproduce the error when `VK_ENABLE_BETA_EXTENSIONS` is defined. Which, leads me to believe that there isn't anything extra that should be done, since the bad stuff is guarded by `VK_ENABLE_BETA_EXTENSIONS`.

I will still add a new tag, as that is useful for those wanting to use the video extensions today, I just don't see a strong need to adjust the v0.6 or any previous commits.

**Comment by charles-lunarg** [comment]
With v0.7 out, this issue should be resolved. Let me know if it doesn't work for you. (aka feel free to reopen the issue)
https://github.com/charles-lunarg/vk-bootstrap/releases/tag/v0.7
