### ISSUE TITLE
Bug in pNext chain code

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#2]
https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp#L158

This line has an extra `&`.

**Comment by charles-lunarg** [comment]
Uh, I believe this is required as pNext is a pointer to the address of the next element in the list. vector.at(0) returns the object at the 0th index, where as pNext needs the address of the first element.

**Comment by martty** [comment]
https://renderdoc.org/vkspec_chunked/chap2.html#fundamentals-validusage-pNext

pNext needs to be a pointer to a valid structure in the chain, not the address of it.

I also noticed the line above has it too.

**Comment by charles-lunarg** [comment]
Ah I see how I was mistaken. Originally, I built up the pNext chain elements were added using the builder function, but later decided that it was simpler to take a vector of pointers and build it when needed. I have since amended the function and added the validation features/enables to the instance builder test in run_test to hopefully exercise said code.
