### ISSUE TITLE
Automate tagging with header updates

### ISSUE THREAD

**Issue by tmayoff** [charles-lunarg/vk-bootstrap#200]
I'd like to be able to add this library to meson's dependency system, I already have a patch for the build, but meson requires the projects to have releases. Could you create at least 1 more recent release and maybe create more periodic releases

**Comment by tmayoff** [comment]
Nevermind, github just kept showing me v0.11 which was 3 years ago, didn't see there were more recent versions

**Comment by charles-lunarg** [comment]
Yes, I would like to make regular releases (based on each header update).

It took me a while to get to this issue because I had other commitments that took priority, plus the fact that the autogen broke and needed special attention.

I'll keep this issue open to track the 'automated release tagging'.

**Comment by charles-lunarg** [comment]
Tag for you to use in meson.
https://github.com/charles-lunarg/vk-bootstrap/releases/tag/v1.3.264

**Comment by charles-lunarg** [comment]
I have added a 'create_tag' workflow which makes it super easy to tag the repo after merging the PR which updates headers. While not 100% automatic, I appreciate being able to review the PR before it merges, rather than potentially breaking main.
