### ISSUE TITLE
Validation Layer does not work properly

### ISSUE THREAD

**Issue by serhathan** [charles-lunarg/vk-bootstrap#234]
Hello, I am currently using Vulkan SDK 1.3.2 and have been following the vkguide tutorial. In the tutorial, this particular library is utilized, and I decided to experiment with it. I followed the steps outlined on vulkantutorial.com, setting up all the necessary Vulkan boilerplate code. However, when attempting a new project and avoiding the manual writing of boilerplate code, I encountered an issue. Specifically, at the end of the chapter (referenced [here](https://vkguide.dev/docs/chapter-1/vulkan_init_code/)), the tutorial suggests destroying the instance to see a validation error. Surprisingly, in my code, I do not encounter this error.

```

void VulkanEngine::cleanup()
{
	if (_isInitialized) {
		//ERROR - Instance destroyed before others
		vkDestroyInstance(_instance, nullptr);

		vkDestroySwapchainKHR(_device, _swapchain, nullptr);

		//destroy swapchain resources
		for (int i = 0; i < _swapchainImageViews.size(); i++) {

			vkDestroyImageView(_device, _swapchainImageViews[i], nullptr);
		}

		vkDestroyDevice(_device, nullptr);
		vkDestroySurfaceKHR(_instance, _surface, nullptr);
		vkb::destroy_debug_utils_messenger(_instance, _debug_messenger);
		SDL_DestroyWindow(_window);
	}
}
```

[ERROR: Validation]
Validation Error: [ VUID-vkDestroyInstance-instance-00629 ] Object 0: handle = 0x24ff02340c0, type = VK_OBJECT_TYPE_INSTANCE; Object 1: handle = 0xf8ce070000000002, type = VK_OBJECT_TYPE_SURFACE_KHR; | MessageID = 0x8b3d8e18 | OBJ ERROR : For VkInstance 0x24ff02340c0[], VkSurfaceKHR 0xf8ce070000000002[] has not been destroyed. The Vulkan spec states: All child objects created using instance must have been destroyed prior to destroying instance (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyInstance-instance-00629)

**Comment by charles-lunarg** [comment]
A better check that validation is setup is to try to create a fence/semaphore with the wrong sType in the create info struct. That is because destroying the instance necessarily means things are shutting down, and this can cause issues where issues that should be reported aren't. Also, 1.3.2 is NOT a valid SDK version, so please update with the actual version.

You can try setting the environment variable VK_LOADER_DEBUG=layer to see which layers are enabled. The lack of output could also mean the debug messenger is setup wrong. How are you creating the debug messenger? For that matter, please just show your instance creation in its entirety.

**Comment by serhathan** [comment]
Firstly, thank you for the quick response.

I'm uncertain about what you meant by "Vulkan 1.3.250 is not valid," so I plan to install the latest version, considering it might be related to SDK versions.

Regarding the issue, I believe the validation layer setup is correct, but it doesn't seem to work properly. The validation layer prints an error`
 [WARNING: General]
Layer VK_LAYER_RTSS uses API version 1.1 which is older than the application specified API version of 1.3. May cause issues.
`
, but unlike the example in the guide, it doesn't display a validation error.I was getting same warning other project as well so i don't think the problem lies there.


My vulkan context create function code:

```
if (_isInitialized)
		return;
	vkb::InstanceBuilder instance_builder;

	auto inst_ret = instance_builder
		.set_app_name("Heart")
		.require_api_version(1, 1)
		.request_validation_layers(true)
		.use_default_debug_messenger()
		.build();

	if (!inst_ret) {
		std::cerr << "Failed to create Vulkan instance. Error: " << inst_ret.error().message() << "\n";
		return;
	}

	vkb::Instance vkbInstance = inst_ret.value();

	_instance = vkbInstance.instance;

	_debugMessenger = vkbInstance.debug_messenger;

	auto res = glfwCreateWindowSurface(_instance, Window::GetGLFWwindow(), nullptr, &_surface);
	//VK_CHECK(res, "Failed to create window surface!");

	vkb::PhysicalDeviceSelector selector{ vkbInstance };

	auto phy_ret = selector
		.set_surface(_surface)
		.set_minimum_version(1, 1)
		.add_required_extensions(_requiredExtensions)
		.select();

	if (!phy_ret) {
		std::cerr << "Failed to select Vulkan Physical Device. Error: " << phy_ret.error().message() << "\n";
		return;
	}

	vkb::PhysicalDevice vkbPhysicalDevice = phy_ret.value();

	_physicalDevice = vkbPhysicalDevice.physical_device;

	vkb::DeviceBuilder device_builder{ phy_ret.value() };
	// automatically propagate needed data from instance & physical device
	auto dev_ret = device_builder.build();

	if (!dev_ret) {
		std::cerr << "Failed to create Vulkan device. Error: " << dev_ret.error().message() << "\n";
		return;
	}

	vkb::Device vkb_device = dev_ret.value();

	_device = vkb_device.device;

	_isInitialized = true;
```

Destroy function code:

```
if (_isInitialized)
	{
               vkDestroyInstance(_instance, nullptr);

		vkDestroyDevice(_device, nullptr);

		vkDestroySurfaceKHR(_instance, _surface, nullptr);

		vkb::destroy_debug_utils_messenger(_instance, _debugMessenger);

		

	}
```

My other project give me error messages like this:

![Ekran Alıntısı](https://github.com/charles-lunarg/vk-bootstrap/assets/58882833/30fd5de1-6a48-4bc8-ab06-8b7073dc5f25)

**Comment by charles-lunarg** [comment]
The initial comment said `Hello, I am currently using Vulkan SDK 1.3.2`, which just means the `50` was accidentally removed. 

Always good to update to the latest SDK when possible.

> [WARNING: General] Layer VK_LAYER_RTSS uses API version 1.1 which is older than the application specified API version of 1.3. May cause issues.

This warning originates from the Vulkan-Loader, not the validation layer. That is very confusing so no worries. It should be safe to ignore, although the VK_LAYER_RTSS layer has been known to cause issues so may be worth disabling if you find an error that is seemingly not due to your code.

Your initialization code looks correct at first glance. I wonder if the output is being 'eaten' by windows. I would suggest putting a breakpoint in the default debug callback in VkBootstrap.h (should be around line 266). That way the debugger should halt upon any message being received by the callback. I use this trick all the time because I can see exactly *when* the validation error occured.

**Comment by serhathan** [comment]
Hello, I installed the latest version of Vulkan and attempted to load the validation layer using `VK_LOADER_DEBUG=layer`. However, the problem persists.

I came across the following resources:
- [Reddit thread](https://www.reddit.com/r/vulkan/comments/j4b8fg/trouble_with_validation_layer_step/)
- [Stack Overflow question](https://stackoverflow.com/questions/68215270/how-to-make-vk-layer-khronos-validation-available)

I attempted to reinstall, but the issue persists. The links suggest deleting residual files, but I'm not sure what that means.

**Comment by serhathan** [comment]
Okay, I've solved it. The problem wasn't with the library itself, but rather, when updating to newer versions of Vulkan, it's necessary to delete all old SDKs (which it was) and residual files in the registry note.
