### ISSUE TITLE
Refactor the `Expected` type to a boost outcome like `Result` type

### ISSUE THREAD

**Issue by LesleyLai** [charles-lunarg/vk-bootstrap#24]
The current implementation of `Expected` in the header is a general-purpose type that mimics the proposed `std::expected`. I propose to change the `Expected<T, E>` to a `Result<T>` type which uses `std::error_code` to represent the error. There are several advantages for this design:
1. We can add Vulkan specific APIs to our `Result` class
2. More ergonomic error reporting with `<system_error>`
3. A type-erased error-code type makes chaining errors easier (especially if we want to pursue monadic extension later)

The downside:
1. Depending on `std::error_code` means pulling in the `<system_error>` header

**Comment by charles-lunarg** [comment]
Thinking back to the initial versions of the expected type, the issue I came across was handling custom vk-bootstrap errors alongside vulkan specific VkResult errors that came from vulkan functions call inside. I believe the issue was that I didn't have type-erasure, so I had to make a custom type which held VkResult's. 
Error handling has been something I would like to see revisited, as the current approach is extremely simplistic and really only handles the 'oops I died' case with little ability to know why.

So this would be a welcome PR and should make for a much more robust library.
And since system_error is C++11, there is no issue in adding it. While I am trying to reduce unnecessary headers, `<system_error>` would make many things simpler with it than without it.
