### ISSUE TITLE
desired_extension deprecated with no replacement?

### ISSUE THREAD

**Issue by hw762** [charles-lunarg/vk-bootstrap#247]
I got warnings about its deprecation. However, it is not documented and there is no replacement

**Comment by charles-lunarg** [comment]
Yes, it will be removed in a future version. There currently is no replacement, however that is because the feature is not suitable in its current form. 

The gist of the problem with the current API is that there is no good way to know what was and wasn't enabled after you selected a physical device. An application must not use things that were not enabled, so this is a rather important thing to know.

See #103 for more details.

**Comment by charles-lunarg** [comment]
I forgot there *is* a replacement.

Once you select your physical device, you can use `enable_extension_if_present` to enable extensions on it, and the return value tells you whether the extension is available.
