### ISSUE TITLE
Cannot pass a const structure to add_pNext

### ISSUE THREAD

**Issue by not-magic** [charles-lunarg/vk-bootstrap#271]
the `add_pNext` calls take non_const pointers, which means you can't pass const structures into it like you would normally do using aggregate initialization without a const_cast.

I'm not a vulkan expert or anything but it seems all the `pNext` here are defined as `const void*` so at least two interfaces should be provided, one taking `const` and the other non const.

**Comment by charles-lunarg** [comment]
Unfortunately, this is not possible with the current implementation.
This is because there isn't any easy way to 'deep-copy' structs in vulkan (not without significant code-generation). Instead, vk-bootstrap takes the pointer to each struct and builds up a pNext chain out of that, adding its own structures to the chain as needed.  `const void*` doesn't solve the problem - I can't modify the structs after they have been added because its a pointer to a const object, not a const pointer to a non-const object.

I mean, I could const_cast away the constness, but that is a worse solution than not providing it in the first place.

**Comment by charles-lunarg** [comment]
After further consideration, the implementation stores pointers to user structs and modifies their contents. It would be very bad to *lie* about this behavior. 
The entire pNext chain implementation could use a make over, as copying user structs would make the API safer as a whole. Unfortunately, that is a low priority among priorities, as the current implementation suffices for most use cases. I'm closing the issue as "not planned"
