### ISSUE TITLE
Selecting distinct transfer queue might select the compute queue

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#3]
That is a validation error. The code only makes it distinct from the gfx queue.

It might also be better to make compute and transfer queues opt-in and not opt-out.

**Comment by charles-lunarg** [comment]
The most recent version tries to find a transfer/compute queue that is distinct from compute/transfer, but fallsback if it can't find it. Should it fail if it can't find a truly distinct queue? Eg, transfer queue that has no graphics or compute capabilities and compute queue that has no graphics or transfer capabilities?

**Comment by martty** [comment]
I think you need to signal failure in that case. Perhaps there can be a weaker requirement, where the application is fine with an aliased queue. (Aliased queues will break multithreading, so this is important info).

this is probably a typo:
https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp#L526

**Comment by charles-lunarg** [comment]
Yes, a seperate 'get_non_unique_but_not_graphics_queue' would suit the situations where the transfer and compute share a queue.
Also, yes that very much is a bug.
This will take a bit more time to flesh out, which means I will have to work on it later. Turns out naming things isn't easy.

**Comment by charles-lunarg** [comment]
I now have it so that you can request a "distinct" or a "dedicated" compute/transfer queue. Distinct means it is distinct from the graphics queue while dedicated means it is just that that queue type.
Eg. Distinct Transfer does transfer and possibly compute but not graphics. Dedicated transfer does transfer but not compute nor graphics.
The bigger issue is that a lot of hardware may have one or the other as dedicated but not both. I *could* do the right thing in the background for the user which would handle the majority of hardware (based off gpuinfo) but alas, its better to be super explicit then hope I get it right.
Closing the issue unless there is anything more to add.
