### ISSUE TITLE
Example: Validation layer error on VkSwapchainCreateInfoKHR

### ISSUE THREAD

**Issue by Axilot** [charles-lunarg/vk-bootstrap#72]
When recreating the swapchain, following validation layer is exposed:
[ERROR: Validation]
Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x5611ea7bf128, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1024,718), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1024,711), minImageExtent = (1024,711), maxImageExtent = (1024,711). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)

**Comment by charles-lunarg** [comment]
This is a 'Not a thing vk-bootstrap can solve' issue, which is why I'm closing it.
This happens because the 'moment' you query the swapchain image extent is possibly not the same moment the OS resizes the window (and thus changing the extent). 

The issue tracking this is here.
https://github.com/KhronosGroup/Vulkan-Docs/issues/1144

If you want a way to ignore this error, get & open VkConfig and add `VUID-VkSwapchainCreateInfoKHR-imageExtent-01274` to the `Mute Message VUIDs` in the settings for the validation layers. This will prevent validation from emitting the message.

**Comment by Axilot** [comment]
Oh, sorry. Makes sense now, thank you.
