### ISSUE TITLE
Error VK_MVK_macos_surface extension is not enabled in the Vulkan instance

### ISSUE THREAD

**Issue by ellipticaldoor** [charles-lunarg/vk-bootstrap#82]
When using vk-bootstrap with SDL2 on a mac I get the following error:

```
VK_MVK_macos_surface extension is not enabled in the Vulkan instance
```

It seems to be that SDL2 is using the old `VK_MVK_macos_surface` extension instead of `VK_EXT_metal_surface` and they have an issue for this https://github.com/libsdl-org/SDL/issues/3906

So basically to make this library work I had to edit the source of `VkBootstrap.cpp` and replace `VK_EXT_metal_surface` in the `added_window_exts` variable for APPLE  with `VK_MVK_macos_surface`

The problem is that when I have to compile to iOS I should instead `VK_MVK_ios_surface`

Could be possible to add an option in the config of the builder to specify a custom `added_window_exts` ?

**Comment by charles-lunarg** [comment]
Thank you for investigating this issue, that definitely make sense as to why its failing. 

What I know is that `enable_extension` does exactly what you need currently (enable an extension) so you can use that to fix the problem right now.

I think there might be a use case for a new function to add window extensions, since its an explicit mechanism to support custom window extensions. But this still means the user has to know which extensions to use.

I thought `metal_surface` was suppose to be the new APPLE extension to rule them all which makes me hesitant to change the logic around which window extensions to enable on apple. My lack of familiarity with macOS/iOS shows here.

**Comment by ellipticaldoor** [comment]
Ah true! this works with `enable_extension` thank you!

I think it's okay to close this issue

**Comment by charles-lunarg** [comment]
I think I'll still add some documentation for whats going on behind the scenes, since it would of helped you here (if you had found it of course)

**Comment by ellipticaldoor** [comment]
I'll leave this since it can help someone else, when using vulkan with this library on macos

You need for the `InstanceBuilder` to set 
```c++
.enable_extension("VK_MVK_macos_surface")
.enable_extension(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME)
```

And for the `PhysicalDeviceSelector` you need to set
```c++
.add_desired_extension("VK_KHR_portability_subset")
```

**Comment by SpaceIm** [comment]
Actually, I believe that relying in client code on `SDL_Vulkan_GetInstanceExtensions()` to inject required extensions during instanciation of `vkb::InstanceBuilder` is more robust.
