### ISSUE TITLE
Loading of libvulkan.1.dylib from the app bundle files conflicts with the one on the Vulkan SDK

### ISSUE THREAD

**Issue by ellipticaldoor** [charles-lunarg/vk-bootstrap#83]
So basically in a mac app you will load the `libvulkan.1.dylib` from a Frameworks folder inside the bundle app.

It looks like VkBootstrap loads this library like this:

```c++
dlopen("libvulkan.1.dylib", RTLD_NOW | RTLD_LOCAL);
```
But I'm not sure why this is needed if I'm linking this library already on my cmake.

It looks like the fist place that VkBootstrap looks for this dylib is `/usr/local/lib/libvulkan.1.dylib` instead of `app_folder.app/Contents/Frameworks/libvulkan.1.dylib`. This will conflict with the rpath of the app which points to the "Resources" and "Frameworks" folder to get the `libMoltenVK.dylib` and icd files.

As soon as I uninstall the Vulkan SDK, VkBootstrap will not find the `/usr/local/lib/libvulkan.1.dylib` and it will load directly from the Frameworks folder of the bundle making the app to run fine.

I'm not very familiar with dlopen and hot it works, how I could make VkBootstrap to load the dylib from the Frameworks folder?

**Comment by charles-lunarg** [comment]
This is effectively putting back the support for dynamically linking (instead of the current dynamic loading). I can do that, and its not a bad option, as it makes the library more configurable.
But, you should be able to avoid loading the library already by providing `vkGetInstanceProcAddr` to either the InstanceBuilder or SystemInfo, whichever you call first. Because you dynamically linked to the vulkan-loader, you should have `vkGetInstanceProcAddr` available and can just 'give' it to vk-bootstrap.

The constructor/functions I am referring to when giving vk-bootstrap `vkGetInstanceProcAddr`
https://github.com/charles-lunarg/vk-bootstrap/blob/0408041547ad96ae05c6aae5c4af60f9b51bd6d9/src/VkBootstrap.h#L278
https://github.com/charles-lunarg/vk-bootstrap/blob/0408041547ad96ae05c6aae5c4af60f9b51bd6d9/src/VkBootstrap.h#L200

**Comment by ellipticaldoor** [comment]
Oh, I actually made a PR https://github.com/charles-lunarg/vk-bootstrap/pull/84/files so this one is wrong right?

Could you show me an example of how to use `vkGetInstanceProcAddr`

**Comment by charles-lunarg** [comment]
You basically just include the vulkan headers, which should provide the prototype of `vkGetInstanceProcAddr`.
Then you pass it into the InstanceBuilder constructor.
```cpp
auto builder = vkb::InstanceBuilder(vkGetInstanceProcAddr)
```

I saw your PR and what makes me unsure about accepting it is that volk looks for both `libvulkan.1.dylib` and `libvulkan.dylib`, while vulkan.hpp only looks for `libvulkan.dylib`. I see how it fixes your problem, but the PR doesn't appear to me to 'solve' the problem universally, just in this situation. Which leads me to believe a more substantial fix (which still could involve looking for `libvulkan.1.dylib` only)  is required.

https://github.com/zeux/volk/blob/b4eb550e2561556db7bf477543d42abd9c4c3217/volk.c#L55
https://github.com/KhronosGroup/Vulkan-Hpp/blob/72d3c3cae61b87bb019ff3a18712e796b635cbb3/vulkan/vulkan.hpp#L10392

**Comment by ellipticaldoor** [comment]
Amazing `vkb::InstanceBuilder(vkGetInstanceProcAddr)` solves this issue.

Should I close this issue then?

**Comment by charles-lunarg** [comment]
I think so, I am not in a position to really 'fix' the issue and the library already has a solution for when dynamically linking the application. It's good you reported the issue as hopefully others with similar problems will either use the solution provided or try to make a PR to do the right thing, which I would gladly accept (my knowledge of macOS specifics is lackluster).
